version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydb" # Set your MongoDB connection string

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - ./mongo-data:/data/db # Persist MongoDB data

networks:
  default:
    driver: bridge