// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Anas Ahmad",
            "url": "https://github.com/anasahmad",
            "email": "anasahmaddev@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/beatsheet": {
            "get": {
                "description": "GET All BeatSheets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BeatSheet"
                ],
                "summary": "GET BeatSheets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "description": "Post BeatSheet from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BeatSheet"
                ],
                "summary": "Post BeatSheet",
                "parameters": [
                    {
                        "description": "BeatSheet Data",
                        "name": "beatSheet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BeatSheet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/beatsheet/:id": {
            "get": {
                "description": "GET BeatSheet by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BeatSheet"
                ],
                "summary": "GET BeatSheet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "put": {
                "description": "Update BeatSheet with the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BeatSheet"
                ],
                "summary": "PUT BeatSheet",
                "parameters": [
                    {
                        "description": "BeatSheet Data",
                        "name": "BeatSheet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BeatSheet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "DELETE BeatSheet by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BeatSheet"
                ],
                "summary": "DELETE BeatSheet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/beatsheet/:id/beat": {
            "post": {
                "description": "Post Beat from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Beat"
                ],
                "summary": "Post Beat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Beat Data",
                        "name": "beat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Beat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/beatsheet/:id/beat/:beatId/act": {
            "post": {
                "description": "Post Act from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Act"
                ],
                "summary": "Post Act",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Beat ID",
                        "name": "beatId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Act Data",
                        "name": "act",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Act"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/beatsheet/:id/beat/:beatId/act/:actId": {
            "put": {
                "description": "Update Act from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Act"
                ],
                "summary": "PUT Act",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Beat ID",
                        "name": "beatId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Act ID",
                        "name": "actId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Act Data",
                        "name": "act",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Act"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "Update Act from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Act"
                ],
                "summary": "PUT Act",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Beat ID",
                        "name": "beatId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Act ID",
                        "name": "actId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/beatsheet/:id/beat/beatId": {
            "put": {
                "description": "PUT Beat from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Beat"
                ],
                "summary": "PUT Beat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Beat ID",
                        "name": "beatId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Beat Data",
                        "name": "beat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Beat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "DELETE Beat from the object in the body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Beat"
                ],
                "summary": "DELETE Beat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BeatSheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Beat ID",
                        "name": "beatId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Act": {
            "type": "object",
            "properties": {
                "cameraAngle": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.Beat": {
            "type": "object",
            "properties": {
                "acts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Act"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.BeatSheet": {
            "type": "object",
            "properties": {
                "beats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Beat"
                    }
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/beatsheet/",
	Schemes:          []string{},
	Title:            "BeatSheet Swagger",
	Description:      "This is a beat sheet service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
